### ISSUE TITLE
Extension Compound Queries does not register 

### ISSUE THREAD

**Issue by revansx** [freephile/qb#4]
### Environment
34.x

### Issue details

Extension SemanticCompoundQueries exists in MezaLocalExtensions/yml but does not appear in the list of registered extensions on Special:Version, nor does its corresponding parser function register.

**Comment by revansx** [comment]
The line:
wfLoadExtension( 'SemanticCompoundQueries' );
never gets written to /opt/.deploy-meza/Extension.php

**Comment by freephile** [comment]
Just merged pull request to fix this error.
